apiVersion: v1
kind: Service
metadata:
  name: node-server
  labels:
    app: node-server
    role: master
    tier: backend
spec:
  ports:
    - name: node-server
      port: 7000
      targetPort: 7000
  selector:
    app: node-server
    role: master
    tier: backend
  type: LoadBalancer
