apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
  type: LoadBalancer # Load balance for an external IP
  # in case we want to ping it from our local machine
